# SAMPLE a.lux CONFIGURATION

adapters.hue:

  # Url under which your Philips Hue can be reached
  url: http://your_hue_address

  # The api key for access to the Hue's api. Get yours as described on https://developers.meethue.com/
  api_key: xyz

