# SAMPLE a.lux CONFIGURATION

# Url under which your Philips Hue can be reached
url: http://hue_address

# The api key for access to the Hue's api. Get yours as described on https://developers.meethue.com/
api_key: your_api_key

# Switch to this scene on the hue to turn on automation by this script.
auto_scene_name: Auto

# Interval in milliseconds during which a.lux will periodically check and update the lights.
refresh_interval: 1000
